sudo: false

language: python
python: 3.7
dist: xenial
sudo: true

python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"

install:
  - python setup.py install

script:
  python src/tests/test.py -v
